#!/usr/bin/env bash
# Configures my ubuntu web server machine
# by installing Nginx listening on port 80 and
# Serve a page that that returns a "Hello World"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up environment.\n"

# Ensure nginx is running
sudo service nginx start

# Set up nginx to listen on port 80
# sudo sed -i 's/^\(.*listen \)80;/\180;/' /etc/nginx/sites-available/default

# Restart nginx (without using systemctl)
sudo /etc/init.d/nginx restart

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
