#!/usr/bin/env bash
# script to install and configure HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers
# Distributes requests using a roundrobin algorithm
#  Ensure that HAProxy can be managed via an init script

sudo apt-get -y update
apt-get -y install haproxy

# editing config file
server_config=\
"
frontend  allan-frontend
        bind *:80
        mode http
        default_backend allan-backend
backend allan-backend
        balance roundrobin
        server 63210-web-01 18.206.207.218:80 check
        server 63210-web-02 54.89.181.222:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
