#!/usr/bin/env bash
# This script displays the number of occurance, IP and HTTP status
# Parses Apache log files in list format
#   Groups visitors by IP and HTTP status code
#+  code of each log, in sorted from greatest to lowest in occurance

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
