#!/bin/bash

# Set path to Gunicorn binary
GUNICORN_BIN="/home/ubuntu/.local/bin/gunicorn"

# Set path to Gunicorn PID file
PID_FILE="/run/hbnb/hbnb.pid"

# Number of workers to gracefully restart
NUM_WORKERS=3

# Gracefully restart Gunicorn
$GUNICORN_BIN -c /path/to/your/gunicorn_config.py --pid $PID_FILE -u ubuntu -g ubuntu --workers $NUM_WORKERS -k gevent --reload

