#!/usr/bin/env bash
#SSH client configuration
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    PasswordAuthentication no
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
